### ISSUE TITLE
Memory leak in pub_encode_gost_ec() with patch

### ISSUE THREAD

**Issue by NMorozxov** [gost-engine/engine#125]
I have already reported this issue for OpenSSL 1.0.2
https://github.com/openssl/openssl/issues/8559

static int pub_encode_gost_ec(X509_PUBKEY *pub, const EVP_PKEY *pk)
if databuf malloc failed, the octec is not freed.
patch that fix this issue
--- engine.orig/gost_ameth.c	2019-03-22 14:15:17.675590270 +0300
+++ engine/gost_ameth.c	2019-03-22 14:19:39.921094584 +0300
@@ -677,6 +677,7 @@
     }
     databuf = OPENSSL_malloc(octet->length);
     if (databuf == NULL) {
+        ASN1_OCTET_STRING_free(octet);
         GOSTerr(GOST_F_PUB_DECODE_GOST_EC, ERR_R_MALLOC_FAILURE);
         ASN1_OCTET_STRING_free(octet);
         return 0;

**Comment by mspncp** [comment]
Note: It might be helpful to make the implementations of the decode and encode function more consistent. While the latter consistently uses the `goto err` pattern, the former doesn't. Also, I see an `OPENSSL_malloc()` vs. `OPENSSL_zalloc()`.

https://github.com/gost-engine/engine/blob/419263293a3075c630d028b94378107714ab6fa6/gost_ameth.c#L678-L683

https://github.com/gost-engine/engine/blob/419263293a3075c630d028b94378107714ab6fa6/gost_ameth.c#L752-L757

**Comment by beldmit** [comment]
Could you please submit a patch?

**Comment by NMorozxov** [comment]
--- engine.orig/gost_ameth.c	2019-03-22 14:15:17.675590270 +0300
+++ engine/gost_ameth.c	2019-03-22 14:19:39.921094584 +0300
@@ -677,6 +677,7 @@
     }
     databuf = OPENSSL_malloc(octet->length);
     if (databuf == NULL) {
+        ASN1_OCTET_STRING_free(octet);
         GOSTerr(GOST_F_PUB_DECODE_GOST_EC, ERR_R_MALLOC_FAILURE);
         ASN1_OCTET_STRING_free(octet);
         return 0;

**Comment by beldmit** [comment]
Sorry, do not get an idea. 
The octet ASN1_STRING is freed 2 lines below.

**Comment by NMorozxov** [comment]
Sorry i just repeated the patch from 1.0.2, in this time it is realy no nedd

**Comment by mspncp** [comment]
@beldmit sorry if my https://github.com/gost-engine/engine/issues/125#issuecomment-475588605 was not clear enough:

In https://github.com/openssl/openssl/issues/8559#issue-424136615, @NMorozxov originally reported _two_ leaks where `octet` was not free'd in the error path, one in `pub_decode_gost_ec` and one in `pub_decode_gost_ec`.

To me it looks like the leak in `pub_decode_gost_ec` is fixed in this code, but the leak in `pub_decode_gost_ec` still exists:

https://github.com/gost-engine/engine/blob/419263293a3075c630d028b94378107714ab6fa6/gost_ameth.c#L753-L757

In the error path there is a jump to the `err:` label, but I don't see `octet` being free'd there:

https://github.com/gost-engine/engine/blob/419263293a3075c630d028b94378107714ab6fa6/gost_ameth.c#L777-L785

**Comment by beldmit** [comment]
@mspncp, got the idea. As octet is not allocated at the moment of allocating the databuf, I've missed that it should be freed anyway (a malloc failure may occur at line 770).

So moving the ```ASN1_BIT_STRING_free(octet);``` below the err label should fix it.

**Comment by mspncp** [comment]
> So moving the ASN1_BIT_STRING_free(octet); below the err label should fix it.

Yes, that fixes the leak for `pub_encode_gost_ec`. But please note that IMHO there is a deeper problem causing this leak, which should be fixed, too:

While the implementations of `pub_decode_gost_ec` and `pub_enccode_gost_ec` are very similar (because they are more or less inverses of each other), their error handling is completely different: While `pub_encode_gost_ec` prefers using the `goto err` pattern, the function `pub_decode_gost_ec` prefers to cleanup individually and `return 0;`.

This difference of implementations is an inconsistency and inconsistency is an unnecessary source of errors.

In my opinion the `goto err` pattern is safer and less error prone, because it is easy to follow and guarantees automatic cleanup when the execution leaves the scope of the function, in the both the success and error paths. So if it was my code, I would harmonize the error handling.
