### ISSUE TITLE
Make engine usable as a shared library

### ISSUE THREAD

**Issue by vt-alt** [gost-engine/engine#202]
Some users would greatly prefer to link against gost-engine as a library and not use it as `dlopen` object. This is more secure and would free user from messing with `--engine` options, or configs, or env variables.

1. Is this forbidden by OpenSSL policy and should be feature requested in OpenSSL first?
2. I first request a principal agreement for this as a valid goal.
3. Then suggestions on how to implement this correctly.

(Adding ppl who may be interested to discuss this: @glebfm @ldv-alt @levitte).

ps. (Based on #165 but a contrary idea.)

**Comment by beldmit** [comment]
Hmmm. I'm not sure it's worth implementing. The engine shouldn't be treated as a self-contained product.

**Comment by ldv-alt** [comment]
On Wed, Jan 15, 2020 at 03:54:38AM -0800, Dmitry Belyavskiy wrote:
> Hmmm. I'm not sure it's worth implementing. The engine shouldn't be treated as a self-contained product.

If I understand correctly, the suggestion is not to make a self-contained
library out of gost-engine, but to create a library form of gost-engine
that could be linked with instead of using dlopen/dlsym, so that all
dynamic linking checks could be performed automatically by ld.so at
startup.

**Comment by levitte** [comment]
It's absolutely possible to do this. It probably needs the same extra coding that you see in static engines, which affects both the engine and the application that uses it... or come to think of it, it might be possible to only have all the extra coding in the engine, with a couple of constructor/destructor functions (I have not tested this, at all)

**Comment by beldmit** [comment]
@vt-alt, could you please make a draft patch?

**Comment by vt-alt** [comment]
If everybody agrees, this is great news. Thanks!

> @vt-alt, could you please make a draft patch?

I will try. But, as this is not so trivial, I need to think it over and research how to do it better.

**Comment by levitte** [comment]
Side note: I will have a look to see if this kind of construct can be done with providers. I actually think that may be easier than with engines...

**Comment by levitte** [comment]
Revisiting this...

Something that makes it unsuitable as a shared library is that *all* engines that are built as modules have these entry points:

-   bind_engine
-   v_check

So while using *one* engine module as a shared library is fine (except not on some MacOS versions, they are stricter with the type of the dynamically loadable thing), if someone wants to use more than one engine with their app and try to link with the engine modules, they are royally screwed.

It is, however, possible to build an engine as a library, and it doesn't really matter if it's a static or shared library.  The point is that you should then have unique entry points for each such library instead of bind_engine and v_check (actually, v_check is usually not necessary in that scenario).  If you look at the engines that are bundled in OpenSSL's source, you'll see something like this, where NAME is the name of the engine:

``` C
static int bind_NAME(ENGINE *e)
{
    /* contains code that populates |e| with diverse ENGINE_set_ calls */
}

#ifndef OPENSSL_NO_DYNAMIC_ENGINE
static int bind_helper(ENGINE *e, const char *id)
{
    if (id && (strcmp(id, engine_NAME_id) != 0))
        return 0;
    if (!bind_ossltest(e))
        return 0;
    return 1;
}

IMPLEMENT_DYNAMIC_CHECK_FN()
IMPLEMENT_DYNAMIC_BIND_FN(bind_helper)
#else
void load_NAME(void)
{
    ENGINE *toadd = ENGINE_new();

    if (toadd && bind_NAME(toadd))
        ENGINE_add(toadd); /* libcrypto increments structural reference here */
    ENGINE_free(toadd);
    ERR_clear_error();
}
#endif
```

This means that if an application prefers to link with an engine in shared library form, they will also need to call `load_NAME()` to add it...  and the engine in library form needs to *not* define `bind_engine` and `v_check`, to avoid clashes.

**Comment by levitte** [comment]
What I would recommend is to offer `gost.so` as a dynamically loadable module (with dlopen() and friends) and libgost.so for applications where linking with it is prefered.

**Comment by levitte** [comment]
What has happened recently is that the engine code itself is very minimal:

https://github.com/gost-engine/engine/blob/dd06acfd99c408fdee066f614ea22bce1d393830/CMakeLists.txt#L182-L184

Everything else is in the gost_core library.  It's still possible to make a shared library version of the engine...  is that still desirable, i.e. basically having the option of loading the engine by calling `ENGINE_load_gost()`?  (I discovered that this function still exists)

**Comment by vt-alt** [comment]
I believe it's still desirable, but so far not much time to spend on it. Also, I am not great at understanding implications of macos, but it seem special.

**Comment by levitte** [comment]
Well, you don't have to look at macos, it's enough to think about linking with *two* engines as shared libraries and realise how much their `bind_engine` and `v_check` will clash :wink:

Anyway, I've already done the maneuver with the provider implementation, it's quite easy to do the same for the engine.  I'll submit a PR later this evening.

**Comment by levitte** [comment]
@vt-alt et all, please see #316.

**Comment by levitte** [comment]
Should this be closed now?
